---
- hosts: all
  become: yes
  tasks:
  - name: install webserver
    dnf:
       name: httpd
       state: present

  - name: start webserver on nodes
    service:
       name: httpd
       state: reloaded